[package]
name = "bimhd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtfs-structures = "0.41.2"
trigram = "0.4.4"

[[bin]]
name = "bimhd"
path = "src/main.rs"